### ISSUE TITLE
No Member setAPIKey

### ISSUE THREAD

**Issue by jaympatel1893** [trnql/trnql_ios#1]
I followed the instruction given on the quickstart page. Installed using cocoapods, applied build settings.
Here is the error in settingAPI.

Type Trnql has no member "setAPIKey"

**Comment by trnql** [comment]
@jaympatel1893 Apologies, there was a mistake in the Quickstart Guide. Please set your API key with `Trnql.apiKey = "INSERT_YOUR_KEY_HERE"`

**Comment by jaympatel1893** [comment]
Even the delegate method is not working!
